import requests

burp0_url = "http://localhost:5000/"
burp0_headers = {"Cache-Control": "max-age=0",
                 "sec-ch-ua": "\"Not/A)Brand\";v=\"8\", \"Chromium\";v=\"126\"",
                 "sec-ch-ua-mobile": "?0",
                 "sec-ch-ua-platform": "\"Windows\"",
                 "Accept-Language": "en-US",
                 "Upgrade-Insecure-Requests": "1", 
                 "Origin": "http://localhost:5000",
                 "Content-Type": "application/x-www-form-urlencoded",
                 "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.6478.127 Safari/537.36",
                 "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
                 "Sec-Fetch-Site": "same-origin",
                 "Sec-Fetch-Mode": "navigate", 
                 "Sec-Fetch-User": "?1",
                 "Sec-Fetch-Dest": "document",
                 "Referer": "http://localhost:5000/", 
                 "Accept-Encoding": "gzip, deflate, br",
                 "Connection": "keep-alive"}

sentences = [
    "The quick brown fox jumps over the lazy dog.",
    "She sells seashells by the seashore.",
    "How much wood would a woodchuck chuck if a woodchuck could chuck wood?",
    "A journey of a thousand miles begins with a single step.",
    "To be or not to be, that is the question.",
    "All that glitters is not gold.",
    "The early bird catches the worm.",
    "A penny saved is a penny earned.",
    "Actions speak louder than words.",
    "Beauty is in the eye of the beholder.",
    "Beggars can’t be choosers.",
    "Better late than never.",
    "Birds of a feather flock together.",
    "Cleanliness is next to godliness.",
    "Don’t bite the hand that feeds you.",
    "Don’t count your chickens before they hatch.",
    "Don’t judge a book by its cover.",
    "Every cloud has a silver lining.",
    "Fools rush in where angels fear to tread.",
    "Fortune favors the bold.",
    "Good things come to those who wait.",
    "Honesty is the best policy.",
    "Hope for the best, but prepare for the worst.",
    "If it ain’t broke, don’t fix it.",
    "If you can’t beat them, join them.",
    "It’s better to have loved and lost than never to have loved at all.",
    "It’s no use crying over spilt milk.",
    "Laughter is the best medicine.",
    "Let sleeping dogs lie.",
    "Look before you leap.",
    "Money doesn’t grow on trees.",
    "Necessity is the mother of invention.",
    "No man is an island.",
    "One good turn deserves another.",
    "Out of sight, out of mind.",
    "Practice makes perfect.",
    "Rome wasn’t built in a day.",
    "The pen is mightier than the sword.",
    "The squeaky wheel gets the grease.",
    "There’s no place like home.",
    "There’s no such thing as a free lunch.",
    "Time heals all wounds.",
    "To err is human, to forgive divine.",
    "Two heads are better than one.",
    "When in Rome, do as the Romans do.",
    "When the going gets tough, the tough get going.",
    "Where there’s a will, there’s a way.",
    "You can’t have your cake and eat it too.",
    "You can’t judge a book by its cover.",
    "You can’t make an omelette without breaking eggs.",
    "You reap what you sow.",
    "Absence makes the heart grow fonder.",
    "A picture is worth a thousand words.",
    "A watched pot never boils.",
    "All’s fair in love and war.",
    "An apple a day keeps the doctor away.",
    "As you sow, so shall you reap.",
    "Barking dogs seldom bite.",
    "Beauty is only skin deep.",
    "Better safe than sorry.",
    "Bird in the hand is worth two in the bush.",
    "Blood is thicker than water.",
    "Charity begins at home.",
    "Clothes make the man.",
    "Curiosity killed the cat.",
    "Discretion is the better part of valor.",
    "Don’t put all your eggs in one basket.",
    "Early to bed and early to rise makes a man healthy, wealthy, and wise.",
    "Every rose has its thorn.",
    "Familiarity breeds contempt.",
    "Fish and visitors smell after three days.",
    "Give a man a fish and you feed him for a day.",
    "God helps those who help themselves.",
    "Great minds think alike.",
    "He who laughs last laughs best.",
    "Hindsight is 20/20.",
    "If at first you don’t succeed, try, try again.",
    "If the shoe fits, wear it.",
    "Ignorance is bliss.",
    "Imitation is the sincerest form of flattery.",
    "It takes two to tango.",
    "Knowledge is power.",
    "Lend a helping hand.",
    "Lightning never strikes twice in the same place.",
    "Like father, like son.",
    "Live and let live.",
    "Look before you leap.",
    "Make hay while the sun shines.",
    "Misery loves company.",
    "No pain, no gain.",
    "Old habits die hard.",
    "One man’s trash is another man’s treasure.",
    "Only time will tell.",
    "Opposites attract.",
    "Patience is a virtue.",
    "Practice makes perfect.",
    "The early bird catches the worm.",
    "The grass is always greener on the other side.",
    "There’s no place like home.",
]

burp0_data = {"comment": "asa"}
for item in sentences:
    requests.post(burp0_url, headers=burp0_headers, data={"comment": item})